### ISSUE TITLE
Trouble installing 

### ISSUE THREAD

**Issue by g-goessel** [MatthieuLemoine/open-image-feed#27]
Hi,
I am trying to install and when I run `npm run build` I have this error message :
```
ERROR in ./common/actions/posts/posts.js
Module not found: Error: Cannot resolve module 'socket.io-client/socket.io' in /var/lib/oif/open-image-feed/common/actions/posts
 @ ./common/actions/posts/posts.js 219:191-228
```
I tried to find a solution but I failed (I am new to nodeJS).
My system is debian jessie (8).
Thanks

**Comment by MatthieuLemoine** [comment]
@g-goessel  it seems the way of requiring socket.io-client has been updated. It's now fixed.

Thanks for the heads up !
